"""
===========================================================
TradePilotAI
Performance Report
===========================================================

Provides a single interface to all backtest performance
statistics.
"""

from backtesting.backtest_result import BacktestResult


class PerformanceReport:
    """
    High-level interface for analysing a completed backtest.
    """

    def __init__(self, result: BacktestResult):
        self._result = result

    @property
    def result(self) -> BacktestResult:
        """
        Underlying backtest result.
        """
        return self._result

    @property
    def analytics(self):
        """
        Portfolio analytics.
        """
        return self.result.analytics

    @property
    def portfolio(self):
        """
        Portfolio used during the backtest.
        """
        return self.result.portfolio

    @property
    def equity_curve(self):
        """
        Equity curve generated by the backtest.
        """
        return self.result.equity_curve

    @property
    def win_rate(self) -> float:
        """
        Percentage of winning trades.
        """

        if self.analytics.total_trades == 0:
            return 0.0

        return (
            self.analytics.winning_trades
            / self.analytics.total_trades
        ) * 100

    @property
    def profit_factor(self) -> float:
        """
        Gross profit divided by gross loss.
        """

        gross_profit = self.analytics.realised_profit
        gross_loss = abs(self.analytics.realised_loss)

        if gross_loss == 0:
            return 0.0

        return gross_profit / gross_loss