"""
===========================================================
TradePilotAI
Trade Signal
===========================================================

Represents a trading signal generated by a strategy.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from signals.signal_types import SignalType


@dataclass(slots=True)
class TradeSignal:
    """
    Represents a request to enter or exit a trade.
    """

    symbol: str
    action: SignalType
    entry_price: float

    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None

    strategy: str = "Unknown"

    confidence: float = 1.0

    timestamp: datetime = field(default_factory=datetime.now)

    notes: str = ""

    @property
    def is_buy(self) -> bool:
        return self.action == SignalType.BUY

    @property
    def is_sell(self) -> bool:
        return self.action == SignalType.SELL

    @property
    def risk_per_share(self) -> float | None:
        """
        Returns the monetary risk per share if a stop-loss exists.
        """
        if self.stop_loss is None:
            return None

        return abs(self.entry_price - self.stop_loss)